{
 "title": "Flow Records Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Flow Records Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "flowEndSeconds",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count()\nFROM $table\nWHERE $timeFilter\n",
     "rawQuery": "SELECT count()\n\nFROM default.antrea\n\nWHERE\n    flowEndSeconds >= toDateTime(1637132400) AND flowEndSeconds <= toDateTime(1637135566)\n    AND sourcePodName = 'flow-aggregator-5f5998cc58-8z97k'",
     "round": "0s",
     "table": "antrea"
    }
   ]
  },
  {
   "title": "Flow Records Count Time Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "flowEndSeconds",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count() as count\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(flowEndSeconds), 1) * 1) * 1000 as t,\n    count() as count\nFROM default.antrea\n\nWHERE flowEndSeconds >= toDateTime(1637559924) AND flowEndSeconds <= toDateTime(1637560224)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "antrea"
    }
   ]
  },
  {
   "title": "Flow Records Table",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "flowEndSeconds",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    sourceIP, destinationIP, sourcePodName, destinationPodName, bytesDelta\nFROM $table\n\nWHERE $timeFilter\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(flowEndSeconds), 30) * 30) * 1000 as t,\n    sourceIP, destinationIP, sourcePodName, destinationPodName, bytesDelta\nFROM default.antrea\n\nWHERE flowEndSeconds >= toDateTime(1637132400) AND flowEndSeconds <= toDateTime(1637164799)\n\nORDER BY t",
     "round": "0s",
     "table": "antrea"
    }
   ]
  }
 ]
}