name: Build, sign and upload plugin

on:
  release:
    types:
      - created

jobs:
  build-plugin:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build and sign plugin
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY}}
          TAG: ${{ github.ref }}
        run: |
          yarn install --pure-lockfile
          yarn build
          npx @grafana/toolkit plugin:sign --rootUrls http://localhost:3000
          zip grafana-custom-plugin-"${TAG:10}".zip dist -r
      - name: Upload grafana-custom-plugin zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./grafana-custom-plugin-"${TAG:10}".zip
          asset_name: grafana-custom-plugin-"${TAG:10}".zip
          asset_content_type: application/zip
